---
# tasks file for run_configure_ec2
 - name: Run and configure ec2 instance
   ec2:
     aws_access_key: AKIAJQGJBGCTWRCMXY3Q
     aws_secret_key: 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
     region: us-west-2
     image: ami-835b4efa
     count: 1
     instance_type: t2.micro
     wait: yes
     wait_timeout: 500
     group: "{{ sec_grp_name }}"
     key_name: OregonKPhom
   register: ec2_instance
 - name: Display instance created
   shell: echo "{{ item }}" > ~/ec2_details
   with_items: "{{ ec2_instance.items }}"
